import {
  CanActivate,
  ExecutionContext,
  Injectable,
  UnauthorizedException,
  mixin,
  Type,
} from "@nestjs/common";
import { JwtService } from "@nestjs/jwt";
import type {
  AuthenticatedRequest,
  AuthRole,
  AuthUser,
} from "../types/authenticated-request";

/**
 * Creates a role-scoped JWT guard for admin or customer routes.
 */
export function JwtRoleGuard(...roles: AuthRole[]): Type<CanActivate> {
  @Injectable()
  /**
   * Runtime guard generated by `JwtRoleGuard`.
   */
  class RoleGuard implements CanActivate {
    constructor(private readonly jwtService: JwtService) {}

    /**
     * Verifies bearer token and checks the requested role set.
     */
    async canActivate(context: ExecutionContext) {
      const request = context.switchToHttp().getRequest<AuthenticatedRequest>();
      const authorization = request.headers.authorization;
      const token = authorization?.startsWith("Bearer ") ? authorization.slice(7) : undefined;

      if (!token) {
        throw new UnauthorizedException("Missing bearer token");
      }

      try {
        const payload = await this.jwtService.verifyAsync<AuthUser>(token);
        if (!roles.includes(payload.role)) {
          throw new UnauthorizedException("Invalid token role");
        }
        request.user = payload;
        return true;
      } catch {
        throw new UnauthorizedException("Invalid bearer token");
      }
    }
  }

  return mixin(RoleGuard);
}
