import type { ErrorCode } from "../exceptions/error-code.enum";

/**
 * Standard shape returned by failed HTTP requests.
 */
export interface ApiErrorResponse {
  /** Whether the request succeeded. */
  success: false;
  /** Stable machine-readable error code. */
  code: ErrorCode | string;
  /** HTTP status code. */
  statusCode: number;
  /** Human-readable error message. */
  message: string | string[];
  /** Optional structured error details. */
  details?: unknown;
  /** ISO timestamp generated by the API gateway layer. */
  timestamp: string;
  /** Request path that produced the error. */
  path: string;
}
