/**
 * Standard shape returned by successful HTTP requests.
 *
 * Controllers should return business data directly. The global response
 * interceptor wraps it into this envelope so every client receives a stable
 * contract.
 */
export interface ApiResponse<T> {
  /** Whether the request succeeded. */
  success: true;
  /** Successful response payload. */
  data: T;
  /** ISO timestamp generated by the API gateway layer. */
  timestamp: string;
}
